spring.application.name=Department-Management
spring.security.user.name=sujal
spring.security.user.password=sujal
spring.datasource.url=jdbc:postgresql://localhost:5432/Department
spring.datasource.username=postgres
spring.datasource.password=root
server.port=${PORT:8080}
spring.jpa.hibernate.auto-update=update